### PR TITLE
Update website for 2.4.0 release

### PR DESCRIPTION
**Pull request by pnoltes**
Update for 2.4.0 release, including updated news section

### CODE REVIEW

**Review by PengZheng — APPROVED** [review]
LGTM

**Comment by PengZheng** [comment]
Severity HIGH security problem to be announced with curl 8.4.0 on Oct 11https://github.com/curl/curl/discussions/12026

Though downstream users could easily override libcurl requirement using Conan to build Celix against latest libcurl, we should evaluate whether Celix is affected and make sure Celix can function normally when using libcurl that has fixed this security issue.

I am not sure if our conanfile.py should be updated for this 2.4.0 release or we need an immediate 2.4.1 release.

WDYT? @pnoltes @rlenferink

**Comment by pnoltes** [comment]
> I am not sure if our conanfile.py should be updated for this 2.4.0 release or we need an immediate 2.4.1 release.

I agree. If i am correct we need to wait for the 11 oct curl release and then test whether we can update this in the master branch and for 2.4.1 release. 
Although we just did a release, I think it is good to setup a support branch structure and the curl CVE issues seems a good reason to also do this directly.

I created an issue for this: apache/celix#667

**Comment by pnoltes** [comment]
The docs page for Apache Celix 2.4.0 was not yet working. I udpated the readme and extract celix docs to improve this.

**Pull request merged**
